### ISSUE TITLE
Generator cannot handle empty schema

### ISSUE THREAD

**Issue by aburmeis** [openapi-processor/openapi-processor-core#92] opened 2022-04-13 15:20 UTC
I have a read only part of an API where the content has no schema. At this point a Javascript `any`or Java `Object` would be the appropriate representation. Looking for the OpenApi specification for that, an empty schema seems to be the right definition (see SO https://stackoverflow.com/a/43328994/12890):

    components:
      schemas:
        AnyValue: {}

Doing so this type is not generated nor replaced by Object, it is simply not handled. Even an explicit type mapping (to java.lang.Object e.g.) is ignored so the generated code is not compiling.

The only work around I found looks like this (I don't need array):

    AnyValue:
      anyOf:
        - type: object
        - type: string
        - type: number
        - type: integer
        - type: boolean

and an explicit type mapping

    map:
      types:
        - type: AnyValue => java.lang.Object

I am using `openapi-processor-maven-plugin` version 2021.1 with `openapi-processor-spring` version 2022.2.

**Comment by hauner** [comment] 2022-04-14 06:20
The empty `schema` is a weak spot. I have to look at it. 

That the mapping does not work is unexpected. I wonder what's going wrong there.

**Comment by hauner** [comment] 2022-04-18 15:06
it is now possible and necessary to add a type mapping for this case. 

That the processor does not generate code for the empty schema is caused by another case that must not generate a class. 

Nothing I want to touch right now, so I just added the missing mapping possibility for now.

**Comment by hauner** [comment] 2022-04-19 07:52
released in `io.openapiprocessor:openapi-processor-spring:2022.3`

**Closed by hauner** 2022-04-19 07:52 UTC

**Comment by aburmeis** [comment] 2022-04-19 08:15
Works now with 2022.3, thank you!
